version: '3.5'

services:
  cache:
    image: redis
    ports:
      - "6379:6379"

  api:
    build:
      dockerfile: Dockerfile.dev
      context: .
    # this is for restart server when new change happen
    volumes:
      - .:/app
    env_file:
    - .env.dev
    command: yarn start:dev
    ports:
      - 3000:3000
    depends_on:
      - cache